// <auto-generated />
using System;
using BlazorForKids.Designer.Domain.Services.License;

namespace BlazorForKids.License;

[BkEmbeddedLicense]
internal static class EmbeddedLicense
{
    internal static readonly LicenseInfo License = new LicenseInfo
    {
        Signature = "SpT+4TGp8ot1AZzQmFo9aEl1MHtTSSZty5VCagFEjXDFJLQHtsOvdXnL1KOm800+Vcw16wSP+aD7tl7/mU2p8dnVy6OwtMx4zTq60CMlU6sYBKZneYvAUf6mNlOwqDMGllEkaRpZ/RicoxTHs7cEA6u0uPn4aTeW+lLBJ55F+p+NUd2+vD11FvOwE4YUhaTY0Pks+Rb3Q6x8dYcBRPGqMuPIb6gk3f9T15QRbNDKnfDXLey1uTBQqMHSlhbcCT8AZRQSpdKoZl0ExwMtLFL13D3x38mXIN5IFQWF/mOfIG9kuMGXd9fGDhRBcdn1oqgJQsJpPrcizEtejjVb30PUjA==",
        Payload = new UserLicenceInfo
        {
            Email = "bumblucian@yahoo.com",
            ApiKey = "38dd8acc-4424-42c0-ab0a-f706ac758c92",
            Subscription = "Demo",
            ExpirationDate = DateTimeOffset.Parse("2030-05-04T00:00:00.0000000-07:00"),
            CreatedDate = DateTimeOffset.Parse("2025-05-23T01:37:58.6153813-07:00"),
            RefreshDate = DateTimeOffset.Parse("2025-05-23T01:37:58.6340087-07:00"),
            LastFrameworkVersion = "9.1.2"
        }
    };
}