// <auto-generated />
using System;
using BlazorForKids.Designer.Domain.Services.License;

namespace BlazorForKids.License;

[BkEmbeddedLicense]
internal static class EmbeddedLicense
{
    internal static readonly LicenseInfo License = new LicenseInfo
    {
        Signature = "lYIZ4v4ektCldsXlqqB0AyDgUe6xGIVVUxJ+5WNsFPzjVB+P3/Oqdc8vkyHDJ438kh885iCBAxj96KpsWrKIIHvw6JdGv0vYSUE1JsrdtQEulD4jUxC6vqi/nbmVb0J2QiFjnSudspFXCJOudk6tOFy0W806ubFPjq8WQ46ckWW/dL1wa5iTJv6rlYEMlHJckFWUHIw1AlU+8pI4JGlEWA2ye5YZLPrpRVzQhhuyIukZHtWd5XPo5nPUnhoo86e5eFyJHeWYk/1zfjhg4uMO9ww+3ZTLC9sKUEUWH1b6FRc/+Du65600VBJyC5AC62ahDm3P7aXA7At7n9tMJ4Keyw==",
        Payload = new UserLicenceInfo
        {
            Email = "bumblucian@yahoo.com",
            ApiKey = "c9e41ef7-61b2-4485-a979-6b780ab002eb",
            Subscription = "Demo",
            ExpirationDate = DateTimeOffset.Parse("2030-05-04T00:00:00.0000000-07:00"),
            CreatedDate = DateTimeOffset.Parse("2025-05-23T05:41:53.6403728-07:00"),
            RefreshDate = DateTimeOffset.Parse("2025-05-23T05:41:53.6555975-07:00"),
            LastFrameworkVersion = "9.1.2"
        }
    };
}